# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "pyyaml>=6.0",
#     "jsonschema>=4.21",
# ]
# ///
"""Supplement Slot Planner CLI.

Subcommands:
  check    validate pillboxes/traits/substances/products/inventory against schemas and cross-references
  plan     build schedule.yaml from non-inactive inventory entries
  doctor   list cleanup and refactor candidates for agent review

Run via: uv run planner.py <subcommand>
"""

import argparse
from difflib import SequenceMatcher
import json
import secrets
import sys
from pathlib import Path

import jsonschema
import yaml

ROOT = Path(__file__).parent
DATA_DIR = ROOT / "data"
SCHEMA_DIR = ROOT / "schema"
SUBSTANCES_DIR = DATA_DIR / "substances"
PRODUCTS_DIR = DATA_DIR / "products"
GOALS_DIR = DATA_DIR / "goals"
INVENTORY_PATH = DATA_DIR / "inventory.yaml"
SCHEDULE_PATH = ROOT / "schedule.yaml"

VALID_LEVELS = {"avoid_strong", "avoid", "prefer", "prefer_strong"}
REGISTERED_NAMESPACES = {
    "intake",
    "effect",
    "class",
    "risk",
    "activity",
    "mechanism",
}
SLOT_META_FIELDS = {"label", "order"}

LEVEL_SCORES = {
    "prefer_strong": 4,
    "prefer": 2,
    "avoid": -2,
    "avoid_strong": -4,
}
BALANCE_WEIGHT = 0.5
PREFER_WITH_BONUS = 3
NANOID_ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyz"
STABLE_ID_SIZE = 10
SIMILAR_SUBSTANCE_THRESHOLD = 0.86


def load_yaml(path: Path) -> object:
    return yaml.safe_load(path.read_text())


def load_schema(name: str) -> dict:
    return json.loads((SCHEMA_DIR / f"{name}.schema.json").read_text())


def schema_errors(data: object, schema_name: str, file_path: Path) -> list[str]:
    schema = load_schema(schema_name)
    validator = jsonschema.Draft202012Validator(
        schema, format_checker=jsonschema.FormatChecker()
    )
    out: list[str] = []
    for err in validator.iter_errors(data):
        loc = "/".join(str(p) for p in err.absolute_path) or "<root>"
        out.append(f"{file_path}: {loc}: {err.message}")
    return out


def display_message(message: str) -> str:
    root = str(ROOT.resolve())
    return message.replace(f"{root}/", "")


SCHEDULE_COMMENTS = {
    "version": [
        "Generated by `uv run planner.py plan`; edit source cards under data/, not this file.",
        "Schema version for the generated schedule format.",
    ],
    "summary": [
        "Short human-facing summary.",
        "`take` is grouped by pillbox so daily and training products do not read as one regimen.",
        "Review `action_points` before using the schedule.",
    ],
    "action_points": [
        "Highest-signal review actions from warnings and planner constraints.",
        "These are prompts for human review, not medical advice.",
    ],
    "review_contexts": [
        "Grouped review checklist derived from warnings.",
        "Use this to scan practical concern areas before reading detailed warnings.",
    ],
    "placement_notes": [
        "Non-warning placement compromises.",
        "These explain acceptable but imperfect slot choices; they are not safety warnings.",
    ],
    "pillboxes": [
        "Planned pillboxes and their intake slots.",
        "`products` lists scheduled product names; `substances` expands those products for human review.",
    ],
    "goals": [
        "Goal coverage overview.",
        "`coverage_percent` counts taking goal substances currently active in scheduled inventory.",
    ],
    "warnings": [
        "Detailed review warnings behind action_points.",
        "Warnings are prompts for human review; they are not medical advice.",
    ],
    "kept_together": [
        "Product pairs the planner tried to place in the same slot.",
        "`together` says whether they landed together.",
    ],
    "explanations": [
        "Per-product placement explanation.",
        "`slot` is the chosen slot; `components` lists the product substances that drove scheduling.",
        "`why_here` summarizes why this slot was selected.",
        "`review_tags` are readable traits aggregated from the product substances.",
    ],
}


def dump_schedule_yaml(schedule: dict) -> str:
    rendered = yaml.safe_dump(
        schedule,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
    )
    lines: list[str] = []
    for line in rendered.splitlines():
        key = line.split(":", 1)[0] if line and not line.startswith(" ") else ""
        if key in SCHEDULE_COMMENTS:
            lines.extend(f"# {comment}" for comment in SCHEDULE_COMMENTS[key])
        lines.append(line)
    return "\n".join(lines) + "\n"


def derive_slot_fields(slots_data: dict) -> set[str]:
    fields: set[str] = set()
    for slot in flatten_pillbox_slots(slots_data).values():
        fields.update(k for k in slot if k not in SLOT_META_FIELDS)
    return fields


def flatten_pillbox_slots(slots_data: dict) -> dict[str, dict]:
    slots: dict[str, dict] = {}
    pillboxes = slots_data.get("pillboxes", {}) if isinstance(slots_data, dict) else {}
    if not isinstance(pillboxes, dict):
        return slots

    for pillbox_name, pillbox in sorted(pillboxes.items()):
        if not isinstance(pillbox, dict):
            continue
        inventory_stack = pillbox.get("inventory_stack")
        pillbox_slots = pillbox.get("slots", {})
        if not isinstance(pillbox_slots, dict):
            continue
        for slot_name, slot in sorted(
            pillbox_slots.items(),
            key=lambda kv: kv[1].get("order", 0) if isinstance(kv[1], dict) else 0,
        ):
            if not isinstance(slot, dict):
                continue
            slots[slot_name] = {
                **slot,
                "pillbox": pillbox_name,
                "pillbox_label": pillbox.get("label", pillbox_name),
                "inventory_stack": inventory_stack,
            }
    return slots


def build_empty_schedule_pillboxes(slots_data: dict) -> dict[str, dict]:
    out: dict[str, dict] = {}
    pillboxes = slots_data.get("pillboxes", {}) if isinstance(slots_data, dict) else {}
    if not isinstance(pillboxes, dict):
        return out

    for pillbox_name, pillbox in pillboxes.items():
        if not isinstance(pillbox, dict):
            continue
        out[pillbox_name] = {
            "label": pillbox.get("label", pillbox_name),
            "inventory_stack": pillbox.get("inventory_stack"),
            "slots": {},
        }
        pillbox_slots = pillbox.get("slots", {})
        if not isinstance(pillbox_slots, dict):
            continue
        for slot_name, slot in sorted(
            pillbox_slots.items(),
            key=lambda kv: kv[1].get("order", 0) if isinstance(kv[1], dict) else 0,
        ):
            if not isinstance(slot, dict):
                continue
            out[pillbox_name]["slots"][slot_name] = {
                "label": slot.get("label", slot_name),
                "products": [],
                "substances": [],
            }
    return out


def check_pillbox_slot_ids(slots_data: dict, slots_path: Path) -> list[str]:
    errors: list[str] = []
    seen: dict[str, str] = {}
    pillboxes = slots_data.get("pillboxes", {}) if isinstance(slots_data, dict) else {}
    if not isinstance(pillboxes, dict):
        return errors
    for pillbox_name, pillbox in pillboxes.items():
        if not isinstance(pillbox, dict):
            continue
        pillbox_slots = pillbox.get("slots", {})
        if not isinstance(pillbox_slots, dict):
            continue
        for slot_name in pillbox_slots:
            previous_pillbox = seen.get(slot_name)
            if previous_pillbox is not None:
                errors.append(
                    f"{slots_path}: slot id '{slot_name}' is used in both "
                    f"'{previous_pillbox}' and '{pillbox_name}'; slot ids must be "
                    "unique across pillboxes"
                )
            else:
                seen[slot_name] = pillbox_name
    return errors


def check_traits(
    traits_data: dict, traits_path: Path, slot_fields: set[str]
) -> list[str]:
    errors: list[str] = []
    trait_ids = set(traits_data.get("traits", {}).keys())

    for trait_id, trait in traits_data.get("traits", {}).items():
        ns = trait_id.split(":", 1)[0]
        if ns not in REGISTERED_NAMESPACES:
            errors.append(
                f"{traits_path}: trait '{trait_id}' uses unregistered namespace '{ns}' "
                f"(registered: {sorted(REGISTERED_NAMESPACES)})"
            )

        for sep in trait.get("separate_from") or []:
            if sep not in trait_ids:
                errors.append(
                    f"{traits_path}: trait '{trait_id}' separate_from references "
                    f"unknown trait '{sep}'"
                )

        for i, eff in enumerate(trait.get("effects") or []):
            for key in eff.get("match", {}):
                if key not in slot_fields:
                    errors.append(
                        f"{traits_path}: trait '{trait_id}' effect[{i}] match key "
                        f"'{key}' is not a slot field (known: {sorted(slot_fields)})"
                    )

    return errors


def load_card(path: Path, kind: str) -> tuple[dict | None, str | None]:
    """Load a YAML mapping card. Returns (data, error_message). Either is None."""
    if not path.exists():
        return None, f"{path}: file does not exist"
    try:
        card = load_yaml(path)
    except yaml.YAMLError as e:
        return None, f"{path}: yaml parse error: {e}"
    if card is None:
        return None, f"{path}: empty file"
    if not isinstance(card, dict):
        return None, (
            f"{path}: {kind} top-level must be a mapping, "
            f"got {type(card).__name__}"
        )
    return card, None


def load_substance(sf: Path) -> tuple[dict | None, str | None]:
    """Load a substance card. Returns (data, error_message). Either is None."""
    return load_card(sf, "substance")


def load_product(pf: Path) -> tuple[dict | None, str | None]:
    """Load a product formula card. Returns (data, error_message). Either is None."""
    return load_card(pf, "product")


def normalize_filename_part(value: str) -> str:
    normalized = value.lower().replace("&", " and ").replace("'", "").replace("’", "")
    chars = [char if char.isascii() and char.isalnum() else "_" for char in normalized]
    return "_".join(part for part in "".join(chars).split("_") if part)


def normalize_similarity_text(value: str) -> str:
    normalized = value.lower().replace("&", " and ").replace("'", "").replace("’", "")
    chars = [char if char.isascii() and char.isalnum() else " " for char in normalized]
    return " ".join("".join(chars).split())


def product_brand_slug(product: dict) -> str:
    return normalize_filename_part(str(product.get("brand") or "unknown")) or "unknown"


def product_name_slug(product: dict) -> str:
    return normalize_filename_part(str(product.get("name") or "")) or "product"


def generate_stable_id(prefix: str) -> str:
    token = "".join(secrets.choice(NANOID_ALPHABET) for _ in range(STABLE_ID_SIZE))
    return f"{prefix}_{token}"


def canonical_product_filename(product: dict) -> str:
    product_id = str(product.get("id") or "missing_id")
    return f"{product_brand_slug(product)}__{product_name_slug(product)}__{product_id}.yaml"


def substance_slug(substance: dict) -> str:
    name = str(substance.get("name") or "")
    form = substance.get("form")
    if isinstance(form, str) and form:
        return normalize_filename_part(f"{name} {form}")
    return normalize_filename_part(name)


def canonical_substance_filename(substance: dict) -> str:
    substance_id = str(substance.get("id") or "missing_id")
    return f"{substance_slug(substance)}__{substance_id}.yaml"


def format_substance_candidate(substance_id: str, substance: dict) -> str:
    label = format_substance_name(substance)
    return f"{substance_id} {label}"


def substance_similarity_terms(substance: dict) -> list[tuple[str, bool]]:
    terms: list[tuple[str, bool]] = []

    name = substance.get("name")
    form = substance.get("form")
    if isinstance(name, str):
        if isinstance(form, str):
            terms.append((f"{name} {form}", True))
        else:
            terms.append((name, True))

    for alias in substance.get("aliases") or []:
        if isinstance(alias, str):
            terms.append((alias, False))

    normalized_terms: list[tuple[str, bool]] = []
    for term, is_primary in terms:
        normalized = normalize_similarity_text(term)
        normalized_entry = (normalized, is_primary)
        if normalized and normalized_entry not in normalized_terms:
            normalized_terms.append(normalized_entry)
    return normalized_terms


def similarity_score(
    left_terms: list[tuple[str, bool]],
    right_terms: list[tuple[str, bool]],
) -> float:
    scores: list[float] = []
    for left, left_primary in left_terms:
        for right, right_primary in right_terms:
            if left == right:
                if left_primary or right_primary:
                    return 1.0
                continue
            if left_primary and right_primary:
                scores.append(SequenceMatcher(None, left, right).ratio())
    return max(scores) if scores else 0.0


def substance_name_key(substance: dict) -> str:
    name = substance.get("name")
    if not isinstance(name, str):
        return ""
    return normalize_similarity_text(name)


def substance_display_name(substance: dict) -> str:
    name = substance.get("name")
    if isinstance(name, str) and name:
        return name
    return str(substance.get("id") or "Unknown substance")


def connected_components(edges: dict[str, set[str]]) -> list[list[str]]:
    seen: set[str] = set()
    components: list[list[str]] = []

    for node in sorted(edges):
        if node in seen:
            continue
        stack = [node]
        component: list[str] = []
        seen.add(node)
        while stack:
            current = stack.pop()
            component.append(current)
            for next_node in sorted(edges[current]):
                if next_node in seen:
                    continue
                seen.add(next_node)
                stack.append(next_node)
        if len(component) > 1:
            components.append(sorted(component))
    return components


def substance_cluster_label(substances: dict[str, dict], component: list[str]) -> str:
    name_counts: dict[str, int] = {}
    display_names: dict[str, str] = {}
    for substance_id in component:
        substance = substances[substance_id]
        name_key = substance_name_key(substance)
        if not name_key:
            continue
        name_counts[name_key] = name_counts.get(name_key, 0) + 1
        display_names.setdefault(name_key, substance_display_name(substance))

    if name_counts:
        best_key = sorted(
            name_counts,
            key=lambda key: (-name_counts[key], display_names[key].casefold()),
        )[0]
        return display_names[best_key]

    first_substance = substances[component[0]]
    return substance_display_name(first_substance)


def collect_similar_substances(substances: dict[str, dict]) -> list[str]:
    clusters: list[str] = []
    substance_items = sorted(substances.items())
    terms_by_id = {
        substance_id: substance_similarity_terms(substance)
        for substance_id, substance in substance_items
    }
    edges: dict[str, set[str]] = {substance_id: set() for substance_id in substances}

    for index, (left_id, left_substance) in enumerate(substance_items):
        for right_id, right_substance in substance_items[index + 1 :]:
            same_name = (
                substance_name_key(left_substance)
                and substance_name_key(left_substance) == substance_name_key(right_substance)
            )
            score = similarity_score(terms_by_id[left_id], terms_by_id[right_id])
            if not same_name and score < SIMILAR_SUBSTANCE_THRESHOLD:
                continue
            edges[left_id].add(right_id)
            edges[right_id].add(left_id)

    for component in connected_components(edges):
        label = substance_cluster_label(substances, component)
        entries = [
            format_substance_candidate(substance_id, substances[substance_id])
            for substance_id in component
        ]
        cluster_lines = [label]
        cluster_lines.extend(f"    - {entry}" for entry in sorted(entries, key=str.casefold))
        clusters.append("\n".join(cluster_lines))

    return sorted(clusters, key=lambda cluster: cluster.splitlines()[0].casefold())


def check_substances(
    substance_files: list[Path],
    trait_ids: set[str],
    *,
    prefer_with_registry: dict[str, Path] | None = None,
) -> tuple[list[str], list[str], dict[str, Path]]:
    """Returns (errors, info, substance_ids_to_path_map)."""
    errors: list[str] = []
    info: list[str] = []
    seen_ids: dict[str, Path] = {}
    seen_substances: dict[str, dict] = {}
    prefer_with_refs: list[tuple[Path, str, str]] = []  # (sf, source_id, target_id)
    relation_refs: list[tuple[Path, str, str]] = []  # (sf, source_id, target_id)

    for sf in substance_files:
        substance, err = load_substance(sf)
        if err:
            errors.append(err)
            continue

        errors.extend(schema_errors(substance, "substance", sf))

        sid = substance.get("id")
        if sid:
            expected_filename = canonical_substance_filename(substance)
            if sf.name != expected_filename:
                errors.append(
                    f"{sf}: substance filename must be '{expected_filename}'"
                )
            if sid in seen_ids:
                errors.append(
                    f"{sf}: duplicate id '{sid}' (also in {seen_ids[sid]})"
                )
            else:
                seen_ids[sid] = sf
                substance["_path"] = str(sf)
                seen_substances[sid] = substance

        for tid in substance.get("traits", []):
            if tid not in trait_ids:
                errors.append(f"{sf}: trait '{tid}' not defined in traits.yaml")

        for other in substance.get("prefer_with") or []:
            if sid:
                if other == sid:
                    errors.append(
                        f"{sf}: prefer_with references self ('{sid}')"
                    )
                else:
                    prefer_with_refs.append((sf, sid, other))

        for relation in substance.get("relations") or []:
            if not isinstance(relation, dict) or not sid:
                continue
            for target in relation.get("substances") or []:
                if target == sid:
                    errors.append(f"{sf}: relation references self ('{sid}')")
                elif isinstance(target, str):
                    relation_refs.append((sf, sid, target))

        for concern in substance.get("unmatched_concerns") or []:
            info.append(f"{sf}: unmatched_concern: {concern}")

    # Second pass: validate substance refs against the full id set.
    target_ids = prefer_with_registry or seen_ids
    for sf, source, target in prefer_with_refs:
        if target not in target_ids:
            errors.append(
                f"{sf}: prefer_with target '{target}' has no matching substance card"
            )
    for sf, source, target in relation_refs:
        if target not in target_ids:
            errors.append(
                f"{sf}: relation target '{target}' has no matching substance card"
            )

    if prefer_with_registry is None:
        errors.extend(check_relation_mirrors(seen_substances))

    return errors, info, seen_ids


def check_product_formulas(
    product_files: list[Path], substance_ids: dict[str, Path]
) -> tuple[list[str], list[str], dict[str, Path]]:
    """Returns (errors, info, product_ids_to_path_map)."""
    errors: list[str] = []
    info: list[str] = []
    seen_ids: dict[str, Path] = {}

    for pf in product_files:
        product, err = load_product(pf)
        if err:
            errors.append(err)
            continue

        errors.extend(schema_errors(product, "product", pf))

        pid = product.get("id")
        if pid:
            expected_filename = canonical_product_filename(product)
            if pf.name != expected_filename:
                errors.append(
                    f"{pf}: product filename must be '{expected_filename}'"
                )
            if pid in seen_ids:
                errors.append(
                    f"{pf}: duplicate id '{pid}' (also in {seen_ids[pid]})"
                )
            else:
                seen_ids[pid] = pf

        for i, component in enumerate(product.get("components") or []):
            if not isinstance(component, dict):
                continue
            ref = component.get("substance")
            if ref is None:
                continue
            if ref not in substance_ids:
                errors.append(
                    f"{pf}: components[{i}].substance '{ref}' references unknown "
                    f"substance (expected at data/substances/{ref}.yaml)"
                )

        for concern in product.get("unmatched_concerns") or []:
            info.append(f"{pf}: unmatched_concern: {concern}")

    return errors, info, seen_ids


def check_inventory_alignment(
    inventory_data: dict, product_ids: dict[str, Path]
) -> list[str]:
    """Verify inventory entries reference product cards and flag shelf candidates."""
    errors: list[str] = []
    referenced_products: set[str] = set()

    for iid, entry in normalize_inventory_entries(inventory_data).items():
        if not isinstance(entry, dict):
            continue
        product_ref = entry.get("product")
        if not product_ref:
            continue
        referenced_products.add(product_ref)
        if product_ref not in product_ids:
            stack = entry.get("stack", "<unknown>")
            errors.append(
                f"{INVENTORY_PATH}: stacks.{stack} contains product '{product_ref}' "
                "has no matching product card id under data/products/"
            )

    for pid, pf in product_ids.items():
        if pid not in referenced_products:
            print(
                f"WARN: {INVENTORY_PATH}: product '{pid}' has no inventory "
                f"entry (card at {pf}). Add it to stacks.* if it is on the shelf."
            )

    return errors


def check_inventory_duplicate_items(inventory_data: dict) -> list[str]:
    errors: list[str] = []
    seen: dict[str, str] = {}
    stacks = inventory_data.get("stacks") or {}
    if not isinstance(stacks, dict):
        return errors

    for stack, items in stacks.items():
        if not isinstance(items, list):
            continue
        for item_id in items:
            if not isinstance(item_id, str):
                continue
            previous_stack = seen.get(item_id)
            if previous_stack is not None:
                errors.append(
                    f"{INVENTORY_PATH}: inventory item '{item_id}' appears in "
                    f"multiple stacks: {previous_stack}, {stack}"
                )
            else:
                seen[item_id] = stack
    return errors


def normalize_inventory_entries(inventory_data: dict) -> dict[str, dict]:
    """Return inventory product ids keyed by item id with stack attached in memory."""
    normalized: dict[str, dict] = {}
    stacks = inventory_data.get("stacks") or {}
    if not isinstance(stacks, dict):
        return normalized

    for stack, items in stacks.items():
        if not isinstance(items, list):
            continue
        for product_id in items:
            if not isinstance(product_id, str):
                continue
            normalized[product_id] = {"product": product_id, "stack": stack}
    return normalized


def collect_product_substance_refs(
    products: dict[str, dict], product_ids: set[str]
) -> set[str]:
    refs: set[str] = set()
    for product_id in product_ids:
        product = products.get(product_id)
        if not isinstance(product, dict):
            continue
        refs.update(product_component_substances(product))
    return refs


def relation_target_ids(relation: dict) -> list[str]:
    return [
        target_id
        for target_id in relation.get("substances") or []
        if isinstance(target_id, str)
    ]


def collect_relation_edges(substances: dict[str, dict]) -> set[tuple[str, str, str]]:
    edges: set[tuple[str, str, str]] = set()
    for source_id, substance in substances.items():
        if not isinstance(substance, dict):
            continue
        for relation in substance.get("relations") or []:
            if not isinstance(relation, dict):
                continue
            relation_type = relation.get("type")
            if not isinstance(relation_type, str):
                continue
            for target_id in relation_target_ids(relation):
                edges.add((source_id, relation_type, target_id))
    return edges


def check_relation_mirrors(substances: dict[str, dict]) -> list[str]:
    errors: list[str] = []
    edges = collect_relation_edges(substances)
    substance_paths = {
        substance_id: substance.get("_path", f"substance:{substance_id}")
        for substance_id, substance in substances.items()
    }

    mirror_rules = {
        "balance": "balance",
        "supports": "supported_by",
        "supported_by": "supports",
        "competes": "competes",
        "antagonizes": "antagonized_by",
        "antagonized_by": "antagonizes",
    }
    for source_id, relation_type, target_id in sorted(edges):
        mirror_type = mirror_rules.get(relation_type)
        if mirror_type is None:
            continue
        if (target_id, mirror_type, source_id) in edges:
            continue
        errors.append(
            f"{substance_paths[source_id]}: relation '{relation_type}' to "
            f"'{target_id}' must be mirrored as '{mirror_type}' on '{target_id}'"
        )
    return errors


def collect_missing_balance_relations(
    substances: dict[str, dict],
    active_substances: set[str],
) -> list[dict]:
    warnings: list[dict] = []
    for source_id in sorted(active_substances):
        source = substances.get(source_id)
        if not isinstance(source, dict):
            continue
        for relation in source.get("relations") or []:
            if not isinstance(relation, dict):
                continue
            if relation.get("type") != "balance":
                continue
            for target_id in relation_target_ids(relation):
                if target_id in active_substances:
                    continue
                target = substances.get(target_id) or {"id": target_id}
                reason = relation.get("reason")
                action = relation.get("action")
                warnings.append(
                    {
                        "type": "missing_balance_substance",
                        "source_substance": source_id,
                        "source_name": format_substance_name(source),
                        "target_substance": target_id,
                        "target_name": format_substance_name(target),
                        "reason": reason if isinstance(reason, str) else "",
                        "action": action if isinstance(action, str) else "",
                    }
                )
    return warnings


def collect_missing_support_relations(
    substances: dict[str, dict],
    active_substances: set[str],
) -> list[dict]:
    warnings: list[dict] = []
    for supporter_id, supporter in sorted(substances.items()):
        if not isinstance(supporter, dict):
            continue
        for relation in supporter.get("relations") or []:
            if not isinstance(relation, dict):
                continue
            if relation.get("type") != "supports":
                continue
            for target_id in relation_target_ids(relation):
                if (
                    target_id not in active_substances
                    or supporter_id in active_substances
                ):
                    continue
                target = substances.get(target_id) or {"id": target_id}
                reason = relation.get("reason")
                action = relation.get("action")
                warnings.append(
                    {
                        "type": "missing_support_substance",
                        "source_substance": supporter_id,
                        "source_name": format_substance_name(supporter),
                        "target_substance": target_id,
                        "target_name": format_substance_name(target),
                        "reason": reason if isinstance(reason, str) else "",
                        "action": action if isinstance(action, str) else "",
                    }
                )
    return warnings


def relation_targets(substance: dict, relation_type: str) -> set[str]:
    targets: set[str] = set()
    for relation in substance.get("relations") or []:
        if not isinstance(relation, dict):
            continue
        if relation.get("type") != relation_type:
            continue
        targets.update(relation_target_ids(relation))
    return targets


def substances_have_relation(
    source_id: str,
    target_id: str,
    substances: dict[str, dict],
    relation_type: str,
) -> bool:
    source = substances.get(source_id)
    if not isinstance(source, dict):
        return False
    return target_id in relation_targets(source, relation_type)


def component_sets_have_relation(
    left_components: list[str],
    right_components: list[str],
    substances: dict[str, dict],
    relation_type: str,
) -> bool:
    for left_id in left_components:
        for right_id in right_components:
            if left_id == right_id:
                continue
            if substances_have_relation(left_id, right_id, substances, relation_type):
                return True
            if substances_have_relation(right_id, left_id, substances, relation_type):
                return True
    return False


def collect_intra_product_relation_conflicts(
    *,
    item_id: str,
    product_id: str,
    component_ids: list[str],
    substances: dict[str, dict],
    relation_type: str,
) -> list[dict]:
    conflicts: list[dict] = []
    component_set = set(component_ids)
    seen_pairs: set[frozenset[str]] = set()
    for source_id in component_ids:
        source = substances.get(source_id)
        if not isinstance(source, dict):
            continue
        for relation in source.get("relations") or []:
            if not isinstance(relation, dict):
                continue
            if relation.get("type") != relation_type:
                continue
            for target_id in relation_target_ids(relation):
                if target_id not in component_set or target_id == source_id:
                    continue
                pair_key = frozenset([source_id, target_id])
                if pair_key in seen_pairs:
                    continue
                seen_pairs.add(pair_key)
                conflicts.append(
                    {
                        "type": "intra_product_relation_conflict",
                        "item": item_id,
                        "product": product_id,
                        "relation": relation_type,
                        "source_substance": source_id,
                        "target_substance": target_id,
                        "message": (
                            "Component relation conflicts inside one physical product; "
                            "scheduling keeps the product together and emits this warning"
                        ),
                        "action": relation.get("action", ""),
                    }
                )
    return conflicts


def format_relation_warning(warning: dict) -> str:
    reason = warning.get("reason")
    suffix = f": {reason}" if reason else ""
    return (
        f"{warning['source_substance']} ({warning['source_name']}) -> "
        f"{warning['target_substance']} ({warning['target_name']}){suffix}"
    )


def warning_action(warning_type: str, trait: str, relation: str) -> str:
    if warning_type == "unmatched_concern":
        return "Review unresolved active concerns before treating the schedule as final."
    if warning_type == "intra_product_relation_conflict":
        return "Review this product manually; competing components are inside one physical product and cannot be separated by scheduling."
    if warning_type == "intra_product_trait_conflict":
        return "Review this product manually; its components have conflicting timing preferences."
    if warning_type == "ambiguous_prefer_with":
        return "Choose the intended companion product before relying on co-location."
    if warning_type == "missing_balance_substance":
        return "Review whether the paired balancing substance should be present in the active stack."
    if warning_type == "missing_support_substance":
        return "Review whether adding the supporting substance would improve this target in the active stack."
    if trait == "risk:manual_review":
        return "Review this substance/product context manually before treating the schedule as final."
    if trait == "risk:narrow_therapeutic_window":
        return "Review total daily amount across products and avoid accidental stacking."
    if trait == "risk:hyperkalemia_med_interaction":
        return "Review potassium-related medication context before using this stack."
    if trait in {"risk:fibrinolytic_bleeding", "risk:antiplatelet_bleeding"}:
        return "Review combined bleeding-risk context, especially with anticoagulants, antiplatelets, surgery, or procedures."
    if trait == "risk:hypotension_stack":
        return "Review additive blood-pressure lowering context before combining vasodilator or NO-pathway products."
    if relation == "competes":
        return "Keep these substances away from the same slot when they are in separate products."
    return "Review this warning before treating the schedule as final."


WARNING_CATEGORY_LABELS = {
    "intra_product_relation_conflict": "Component conflict inside one product",
    "intra_product_trait_conflict": "Timing conflict inside one product",
    "ambiguous_prefer_with": "Companion product is ambiguous",
    "missing_balance_substance": "Missing balancing substance",
    "missing_support_substance": "Missing supporting substance",
    "unmatched_concern": "Unresolved active concern",
}


REVIEW_CONTEXTS = {
    "bleeding_context": "Bleeding context",
    "blood_pressure": "Blood pressure / vasodilation",
    "intra_product_conflicts": "Intra-product conflicts",
    "missing_pairings": "Missing balance/support pairings",
    "narrow_window_minerals": "Narrow-window minerals",
    "potassium_medication": "Potassium / medication context",
    "timing_conflicts": "Timing conflicts",
    "unmatched_concerns": "Unresolved active concerns",
}


def review_context_key(warning: dict) -> str | None:
    concern = str(warning.get("concern") or "")
    category = str(warning.get("category") or "")
    action = str(warning.get("action") or "")
    text = " ".join([concern, category, action]).lower()

    if "bleeding" in text or "fibrinolytic" in text or "antiplatelet" in text:
        return "bleeding_context"
    if "blood-pressure" in text or "blood pressure" in text or "hypotension" in text:
        return "blood_pressure"
    if "inside one product" in text or "intra-product" in text:
        return "intra_product_conflicts"
    if "missing balance" in text or "missing support" in text or "paired" in text:
        return "missing_pairings"
    if "narrow therapeutic window" in text or "narrow-window" in text:
        return "narrow_window_minerals"
    if "potassium" in text or "hyperkalemia" in text:
        return "potassium_medication"
    if "timing conflict" in text:
        return "timing_conflicts"
    if "unmatched" in text or "unresolved active concern" in text:
        return "unmatched_concerns"
    return None


def warning_subject(warning: dict) -> str:
    for key in ("product", "substance", "source", "target"):
        value = warning.get(key)
        if isinstance(value, str) and value:
            return value
    return "Stack"


def build_review_contexts(warnings: list[dict]) -> list[dict]:
    grouped: dict[str, dict[str, set[str]]] = {}
    for warning in warnings:
        key = review_context_key(warning)
        if key is None:
            continue
        context = grouped.setdefault(key, {"items": set(), "actions": set()})
        context["items"].add(warning_subject(warning))
        action = warning.get("action")
        if isinstance(action, str) and action:
            context["actions"].add(action)

    return [
        {
            "context": REVIEW_CONTEXTS.get(key, key.replace("_", " ").title()),
            "items": sorted(value["items"], key=str.casefold),
            "actions": sorted(value["actions"], key=str.casefold),
        }
        for key, value in sorted(grouped.items())
    ]


def humanize_warning(
    warning: dict,
    *,
    products: dict[str, dict],
    substances: dict[str, dict],
) -> dict:
    warning_type = str(warning.get("type") or "review")
    trait = str(warning.get("trait") or "")
    relation = str(warning.get("relation") or "")
    product_id = warning.get("product")
    product = (
        format_product_name(products.get(product_id) or {"id": product_id})
        if isinstance(product_id, str)
        else None
    )
    out: dict = {
        "category": WARNING_CATEGORY_LABELS.get(
            warning_type,
            "Review",
        )
    }
    if product:
        out["product"] = product

    substance_id = warning.get("substance")
    if isinstance(substance_id, str):
        out["substance"] = format_substance_name(
            substances.get(substance_id) or {"id": substance_id}
        )

    source_id = warning.get("source_substance")
    target_id = warning.get("target_substance")
    if isinstance(source_id, str):
        out["source"] = format_substance_name(
            substances.get(source_id) or {"id": source_id}
        )
    if isinstance(target_id, str):
        out["target"] = format_substance_name(
            substances.get(target_id) or {"id": target_id}
        )

    if trait:
        out["concern"] = trait.split(":", 1)[1].replace("_", " ")
    elif relation:
        out["concern"] = relation.replace("_", " ")
    elif warning_type.startswith("missing_"):
        out["concern"] = warning_type.replace("_", " ")
    else:
        out["concern"] = warning_type.replace("_", " ")

    message = warning.get("message") or warning.get("reason")
    if isinstance(message, str) and message:
        if "operator attention" not in message:
            out["note"] = message
    action = warning.get("action")
    out["action"] = (
        action if isinstance(action, str) and action else warning_action(warning_type, trait, relation)
    )
    return out


def is_generic_manual_review_warning(warning: dict) -> bool:
    return warning.get("trait") == "risk:manual_review"


def build_action_points(warnings: list[dict]) -> list[str]:
    subjects_by_action: dict[str, set[str]] = {}
    for warning in warnings:
        concern = warning.get("concern")
        if concern == "manual review":
            continue
        product = warning.get("product")
        substance = warning.get("substance") or warning.get("source")
        action = warning.get("action")
        if not isinstance(action, str):
            continue
        if warning.get("category") == "Unresolved active concern":
            subject = "Unresolved active concerns"
        else:
            subject = product or substance or "Stack"
        subjects_by_action.setdefault(action, set()).add(str(subject))

    points: list[str] = []
    for action, subjects in subjects_by_action.items():
        subject_list = sorted(subjects, key=str.casefold)
        if len(subject_list) == 1:
            points.append(f"{subject_list[0]}: {action}")
        else:
            points.append(f"{'; '.join(subject_list)}: {action}")
    return points[:8]


def collect_active_unmatched_concerns(
    *,
    active_order: list[str],
    active_components: dict[str, list[str]],
    item_products: dict[str, str],
    products: dict[str, dict],
    substances: dict[str, dict],
) -> list[dict]:
    warnings: list[dict] = []
    seen: set[tuple[str, str, str]] = set()
    for item_id in active_order:
        product_id = item_products[item_id]
        product = products.get(product_id) or {}
        for concern in product.get("unmatched_concerns") or []:
            if not isinstance(concern, str):
                continue
            key = ("product", product_id, concern)
            if key in seen:
                continue
            seen.add(key)
            warnings.append(
                {
                    "type": "unmatched_concern",
                    "item": item_id,
                    "product": product_id,
                    "message": concern,
                }
            )
        for substance_id in active_components[item_id]:
            substance = substances.get(substance_id) or {}
            for concern in substance.get("unmatched_concerns") or []:
                if not isinstance(concern, str):
                    continue
                key = ("substance", substance_id, concern)
                if key in seen:
                    continue
                seen.add(key)
                warnings.append(
                    {
                        "type": "unmatched_concern",
                        "item": item_id,
                        "product": product_id,
                        "substance": substance_id,
                        "message": concern,
                    }
                )
    return warnings


def build_placement_notes(schedule: dict) -> list[dict]:
    notes: list[dict] = []
    for product_name, explanation in schedule.get("explanations", {}).items():
        why_here = [
            note
            for note in explanation.get("why_here", [])
            if isinstance(note, str) and "tradeoff" in note.lower()
        ]
        if not why_here:
            continue
        notes.append(
            {
                "product": product_name,
                "pillbox": explanation.get("pillbox"),
                "slot": explanation.get("slot"),
                "notes": why_here,
            }
        )
    return sorted(notes, key=lambda entry: str(entry["product"]).casefold())


def build_schedule_summary(schedule: dict) -> dict:
    take: dict[str, list[str]] = {}
    for pillbox_name, pillbox in schedule.get("pillboxes", {}).items():
        lines: list[str] = []
        for slot in pillbox.get("slots", {}).values():
            if not slot.get("products"):
                continue
            lines.append(f"{slot['label']}: {', '.join(slot['products'])}")
        if lines:
            take[pillbox_name] = lines
    return {"take": take}


def collect_goal_substance_refs(goal_files: list[Path]) -> set[str]:
    refs: set[str] = set()
    for gf in goal_files:
        goal, err = load_card(gf, "goal")
        if err:
            continue
        for member in goal.get("members") or []:
            if not isinstance(member, dict):
                continue
            substance_id = member.get("substance")
            if isinstance(substance_id, str):
                refs.add(substance_id)
    return refs


def build_goal_review(
    *,
    goal_files: list[Path],
    active_substances: set[str],
    inactive_substances: set[str],
    substances: dict[str, dict],
) -> list[dict]:
    review: list[dict] = []
    for goal_file in goal_files:
        goal, err = load_card(goal_file, "goal")
        if err:
            continue
        taking_total = 0
        active_count = 0
        covered: list[str] = []
        inactive: list[str] = []
        missing: list[str] = []

        for member in goal.get("members") or []:
            if not isinstance(member, dict):
                continue
            if member.get("status") != "taking":
                continue
            substance_id = member.get("substance")
            if not isinstance(substance_id, str):
                continue
            taking_total += 1
            if substance_id in active_substances:
                active_count += 1
                covered.append(
                    format_substance_name(substances.get(substance_id) or {"id": substance_id})
                )
            elif substance_id in inactive_substances:
                inactive.append(
                    format_substance_name(substances.get(substance_id) or {"id": substance_id})
                )
            else:
                missing.append(
                    format_substance_name(substances.get(substance_id) or {"id": substance_id})
                )

        coverage_ratio = active_count / taking_total if taking_total else 0.0
        goal_entry = {
            "name": goal.get("name"),
            "coverage_percent": round(coverage_ratio * 100),
            "covered": sorted(covered, key=str.casefold),
        }
        if inactive:
            goal_entry["inactive"] = sorted(inactive, key=str.casefold)
        if missing:
            goal_entry["missing"] = sorted(missing, key=str.casefold)
        review.append(goal_entry)

    return review


def collect_orphans() -> dict[str, list[str]]:
    substance_files = sorted(SUBSTANCES_DIR.glob("*.yaml"))
    product_files = sorted(PRODUCTS_DIR.glob("*.yaml"))
    goal_files = sorted(GOALS_DIR.glob("*.yaml")) if GOALS_DIR.exists() else []

    substances: dict[str, dict] = {}
    for sf in substance_files:
        substance, err = load_substance(sf)
        if err:
            continue
        substance_id = substance.get("id")
        if isinstance(substance_id, str):
            substances[substance_id] = substance

    products: dict[str, dict] = {}
    product_substance_refs: set[str] = set()
    for pf in product_files:
        product, err = load_product(pf)
        if err:
            continue
        product_id = product.get("id")
        if isinstance(product_id, str):
            products[product_id] = product
        for component in product.get("components") or []:
            if not isinstance(component, dict):
                continue
            substance_id = component.get("substance")
            if isinstance(substance_id, str):
                product_substance_refs.add(substance_id)

    prefer_with_refs: set[str] = set()
    relation_refs: set[str] = set()
    trait_refs: set[str] = set()
    for substance_id, substance in substances.items():
        if substance.get("prefer_with"):
            prefer_with_refs.add(substance_id)
        for target_id in substance.get("prefer_with") or []:
            if isinstance(target_id, str):
                prefer_with_refs.add(target_id)
        if substance.get("relations"):
            relation_refs.add(substance_id)
        for relation in substance.get("relations") or []:
            if not isinstance(relation, dict):
                continue
            for target_id in relation_target_ids(relation):
                relation_refs.add(target_id)
        for trait_id in substance.get("traits") or []:
            if isinstance(trait_id, str):
                trait_refs.add(trait_id)

    traits_data = load_yaml(DATA_DIR / "traits.yaml")
    traits = traits_data.get("traits", {}) if isinstance(traits_data, dict) else {}
    for trait in traits.values():
        if not isinstance(trait, dict):
            continue
        for target_id in trait.get("separate_from") or []:
            if isinstance(target_id, str):
                trait_refs.add(target_id)

    inventory_data = load_yaml(INVENTORY_PATH)
    inventory_entries = (
        normalize_inventory_entries(inventory_data)
        if isinstance(inventory_data, dict)
        else {}
    )
    inventory_products = {
        entry["product"]
        for entry in inventory_entries.values()
        if isinstance(entry, dict) and isinstance(entry.get("product"), str)
    }
    active_inventory_products = {
        entry["product"]
        for entry in inventory_entries.values()
        if (
            isinstance(entry, dict)
            and entry.get("stack") != "inactive"
            and isinstance(entry.get("product"), str)
        )
    }
    active_substances = collect_product_substance_refs(
        products, active_inventory_products
    )
    inventory_stacks = (
        inventory_data.get("stacks", {}) if isinstance(inventory_data, dict) else {}
    )
    if not isinstance(inventory_stacks, dict):
        inventory_stacks = {}

    slots_data = load_yaml(DATA_DIR / "pillboxes.yaml")
    pillboxes = slots_data.get("pillboxes", {}) if isinstance(slots_data, dict) else {}
    pillbox_stacks = {
        pillbox.get("inventory_stack")
        for pillbox in pillboxes.values()
        if isinstance(pillbox, dict) and isinstance(pillbox.get("inventory_stack"), str)
    }

    substance_refs = (
        product_substance_refs
        | collect_goal_substance_refs(goal_files)
        | prefer_with_refs
        | relation_refs
    )
    unused_substances = sorted(set(substances) - substance_refs)
    products_without_inventory = sorted(set(products) - inventory_products)
    unused_traits = sorted(set(traits) - trait_refs)
    empty_stacks = sorted(
        stack
        for stack, items in inventory_stacks.items()
        if isinstance(items, list) and not items
    )
    stacks_without_pillboxes = sorted(
        set(inventory_stacks) - pillbox_stacks - {"inactive"}
    )
    pillbox_stacks_without_inventory = sorted(pillbox_stacks - set(inventory_stacks))

    return {
        "substances.unused": unused_substances,
        "products.without_inventory": products_without_inventory,
        "traits.unused": unused_traits,
        "stacks.empty": empty_stacks,
        "stacks.without_pillboxes": stacks_without_pillboxes,
        "pillbox_stacks.without_inventory": pillbox_stacks_without_inventory,
        "substances.similar_names": collect_similar_substances(substances),
        "relations.balance_missing": [
            format_relation_warning(warning)
            for warning in collect_missing_balance_relations(
                substances, active_substances
            )
        ],
        "relations.supports_missing": [
            format_relation_warning(warning)
            for warning in collect_missing_support_relations(
                substances, active_substances
            )
        ],
    }


def check_goals(goal_files: list[Path], substance_ids: dict[str, Path]) -> list[str]:
    """Validate goal cards against schema and members[].substance refs."""
    errors: list[str] = []
    for gf in goal_files:
        try:
            goal = load_yaml(gf)
        except yaml.YAMLError as e:
            errors.append(f"{gf}: yaml parse error: {e}")
            continue
        if goal is None:
            errors.append(f"{gf}: empty file")
            continue
        if not isinstance(goal, dict):
            errors.append(f"{gf}: top-level must be a mapping")
            continue

        errors.extend(schema_errors(goal, "goal", gf))
        for i, member in enumerate(goal.get("members") or []):
            if not isinstance(member, dict):
                continue
            ref = member.get("substance")
            if ref is None:
                continue
            if ref not in substance_ids:
                errors.append(
                    f"{gf}: members[{i}].substance '{ref}' has no matching substance card "
                    f"(expected at data/substances/{ref}.yaml)"
                )
    return errors


def report(errors: list[str], info: list[str]) -> int:
    for msg in info:
        print(f"INFO: {display_message(msg)}")
    if errors:
        for e in errors:
            print(f"ERROR: {display_message(e)}", file=sys.stderr)
        print(f"\n{len(errors)} error(s) found", file=sys.stderr)
        return 1
    print("All checks passed.")
    return 0


def validate_inventory(
    inventory_path: Path,
    product_ids: dict[str, Path],
    trait_ids: set[str],
) -> list[str]:
    if not inventory_path.exists():
        return [f"missing: {inventory_path}"]
    try:
        inventory_data = load_yaml(inventory_path)
    except yaml.YAMLError as e:
        return [f"{inventory_path}: yaml parse error: {e}"]
    if not isinstance(inventory_data, dict):
        return [f"{inventory_path}: top-level must be a mapping"]
    errors = schema_errors(inventory_data, "inventory", inventory_path)
    errors.extend(check_inventory_duplicate_items(inventory_data))
    errors.extend(check_inventory_alignment(inventory_data, product_ids))
    return errors


def cmd_check() -> int:
    maintenance_result = run_auto_maintenance(quiet=True)
    if maintenance_result != 0:
        return maintenance_result

    errors: list[str] = []
    info: list[str] = []

    slots_path = DATA_DIR / "pillboxes.yaml"
    traits_path = DATA_DIR / "traits.yaml"

    for required in (slots_path, traits_path):
        if not required.exists():
            return report([f"missing: {required}"], [])

    slots_data = load_yaml(slots_path)
    traits_data = load_yaml(traits_path)

    if not isinstance(slots_data, dict):
        return report([f"{slots_path}: top-level must be a mapping"], [])
    if not isinstance(traits_data, dict):
        return report([f"{traits_path}: top-level must be a mapping"], [])

    errors.extend(schema_errors(slots_data, "pillboxes", slots_path))
    errors.extend(schema_errors(traits_data, "traits", traits_path))

    if errors:
        return report(errors, info)

    errors.extend(check_pillbox_slot_ids(slots_data, slots_path))

    slot_fields = derive_slot_fields(slots_data)
    errors.extend(check_traits(traits_data, traits_path, slot_fields))

    trait_ids = set(traits_data.get("traits", {}).keys())

    all_substance_files = sorted(SUBSTANCES_DIR.glob("*.yaml"))
    s_errors, s_info, substance_ids = check_substances(all_substance_files, trait_ids)
    errors.extend(s_errors)
    info.extend(s_info)

    all_product_files = sorted(PRODUCTS_DIR.glob("*.yaml"))
    p_errors, p_info, product_ids = check_product_formulas(
        all_product_files, substance_ids
    )
    errors.extend(p_errors)
    info.extend(p_info)

    errors.extend(validate_inventory(INVENTORY_PATH, product_ids, trait_ids))
    goal_files = sorted(GOALS_DIR.glob("*.yaml")) if GOALS_DIR.exists() else []
    errors.extend(check_goals(goal_files, substance_ids))

    return report(errors, info)


def rewrite_inventory_product_refs(inventory_data: dict, product_renames: dict[str, str]) -> None:
    stacks = inventory_data.get("stacks") or {}
    if not isinstance(stacks, dict):
        return
    for stack_name, items in stacks.items():
        if not isinstance(items, list):
            continue
        stacks[stack_name] = [
            product_renames.get(item, item) if isinstance(item, str) else item
            for item in items
        ]


def rewrite_substance_refs(data_dir: Path, substance_renames: dict[str, str]) -> None:
    if not substance_renames:
        return

    products_dir = data_dir / "products"
    for path in sorted(products_dir.glob("*.yaml")):
        product, err = load_product(path)
        if err:
            continue
        changed = False
        for component in product.get("components") or []:
            if not isinstance(component, dict):
                continue
            old_ref = component.get("substance")
            if isinstance(old_ref, str) and old_ref in substance_renames:
                component["substance"] = substance_renames[old_ref]
                changed = True
        if changed:
            path.write_text(
                yaml.safe_dump(
                    product,
                    sort_keys=False,
                    default_flow_style=False,
                    allow_unicode=True,
                )
            )

    goals_dir = data_dir / "goals"
    if goals_dir.exists():
        for path in sorted(goals_dir.glob("*.yaml")):
            goal, err = load_card(path, "goal")
            if err:
                continue
            changed = False
            for member in goal.get("members") or []:
                if not isinstance(member, dict):
                    continue
                old_ref = member.get("substance")
                if isinstance(old_ref, str) and old_ref in substance_renames:
                    member["substance"] = substance_renames[old_ref]
                    changed = True
            if changed:
                path.write_text(
                    yaml.safe_dump(
                        goal,
                        sort_keys=False,
                        default_flow_style=False,
                        allow_unicode=True,
                    )
                )

    substances_dir = data_dir / "substances"
    for path in sorted(substances_dir.glob("*.yaml")):
        substance, err = load_substance(path)
        if err:
            continue
        prefer_with = substance.get("prefer_with")
        if not isinstance(prefer_with, list):
            continue
        rewritten = [
            substance_renames.get(item, item) if isinstance(item, str) else item
            for item in prefer_with
        ]
        if rewritten != prefer_with:
            substance["prefer_with"] = rewritten
            path.write_text(
                yaml.safe_dump(
                    substance,
                    sort_keys=False,
                    default_flow_style=False,
                    allow_unicode=True,
                )
            )


def normalize_substances(data_dir: Path) -> tuple[dict[str, str], int] | None:
    substances_dir = data_dir / "substances"
    substance_renames: dict[str, str] = {}
    file_moves: list[tuple[Path, Path]] = []

    for path in sorted(substances_dir.glob("*.yaml")):
        substance, err = load_substance(path)
        if err:
            print(f"ERROR: {display_message(err)}", file=sys.stderr)
            return None

        old_id = substance.get("id")
        generated_id = not isinstance(old_id, str)
        if generated_id:
            substance["id"] = generate_stable_id("sub")
        new_path = substances_dir / canonical_substance_filename(substance)

        if generated_id:
            substance_renames[str(path.stem)] = substance["id"]

        if path != new_path:
            file_moves.append((path, new_path))

        if generated_id:
            path.write_text(
                yaml.safe_dump(
                    substance,
                    sort_keys=False,
                    default_flow_style=False,
                    allow_unicode=True,
                )
            )

    destinations = [destination for _source, destination in file_moves]
    if len(destinations) != len(set(destinations)):
        print(
            "auto-maintenance aborted: duplicate substance filename destination",
            file=sys.stderr,
        )
        return None

    for source, destination in file_moves:
        if destination.exists() and destination != source:
            print(
                "auto-maintenance aborted: destination exists: "
                f"{display_message(str(destination))}",
                file=sys.stderr,
            )
            return None

    for source, destination in file_moves:
        source.rename(destination)

    rewrite_substance_refs(data_dir, substance_renames)
    return substance_renames, len(file_moves)


def run_auto_maintenance(data_dir: Path = DATA_DIR, *, quiet: bool = False) -> int:
    products_dir = data_dir / "products"
    inventory_path = data_dir / "inventory.yaml"

    substance_result = normalize_substances(data_dir)
    if substance_result is None:
        return 1
    substance_renames, substance_file_moves = substance_result

    product_renames: dict[str, str] = {}
    file_moves: list[tuple[Path, Path]] = []

    for path in sorted(products_dir.glob("*.yaml")):
        product, err = load_product(path)
        if err:
            print(f"ERROR: {display_message(err)}", file=sys.stderr)
            return 1

        old_id = product.get("id")
        generated_id = not isinstance(old_id, str)
        if generated_id:
            product["id"] = generate_stable_id("prd")
        new_path = products_dir / canonical_product_filename(product)

        if generated_id:
            product_renames[str(path.stem)] = product["id"]

        if path != new_path:
            file_moves.append((path, new_path))

        if generated_id:
            path.write_text(
                yaml.safe_dump(
                    product,
                    sort_keys=False,
                    default_flow_style=False,
                    allow_unicode=True,
                )
            )

    destinations = [destination for _source, destination in file_moves]
    if len(destinations) != len(set(destinations)):
        print(
            "auto-maintenance aborted: duplicate product filename destination",
            file=sys.stderr,
        )
        return 1

    for source, destination in file_moves:
        if destination.exists() and destination != source:
            print(
                "auto-maintenance aborted: destination exists: "
                f"{display_message(str(destination))}",
                file=sys.stderr,
            )
            return 1

    for source, destination in file_moves:
        source.rename(destination)

    if inventory_path.exists() and product_renames:
        inventory_data = load_yaml(inventory_path)
        if isinstance(inventory_data, dict):
            rewrite_inventory_product_refs(inventory_data, product_renames)
            inventory_path.write_text(
                yaml.safe_dump(
                    inventory_data,
                    sort_keys=False,
                    default_flow_style=False,
                    allow_unicode=True,
                )
            )

    changed = (
        len(substance_renames)
        + substance_file_moves
        + len(product_renames)
        + len(file_moves)
    )
    if changed and not quiet:
        print(
            "normalized substances: "
            f"{len(substance_renames)} ids, {substance_file_moves} filenames"
        )
        for old_id, new_id in sorted(substance_renames.items()):
            print(f"  {old_id} -> {new_id}")
        print(
            "normalized products: "
            f"{len(product_renames)} ids, {len(file_moves)} filenames"
        )
        for old_id, new_id in sorted(product_renames.items()):
            print(f"  {old_id} -> {new_id}")
    return 0


def cmd_doctor() -> int:
    maintenance_result = run_auto_maintenance(quiet=True)
    if maintenance_result != 0:
        return maintenance_result

    sections = collect_orphans()

    print("Doctor / cleanup candidates")
    for section, items in sections.items():
        print(f"\n{section} ({len(items)})")
        if not items:
            print("  none")
            continue
        for item in items:
            print(f"  - {item}")
    return 0


# ============================================================================
# plan: backtracking scheduler
# ============================================================================


def effective_inventory_traits(
    product: dict,
    substances: dict[str, dict],
    traits_data: dict | None = None,
) -> tuple[set[str], dict[str, list[str]], list[dict]]:
    """Aggregate component substance traits for one physical inventory item."""
    effective: set[str] = set()
    trait_sources: dict[str, list[str]] = {}

    for component_id in product_component_substances(product):
        substance = substances.get(component_id)
        if not substance:
            continue
        for trait_id in substance.get("traits") or []:
            effective.add(trait_id)
            trait_sources.setdefault(trait_id, [])
            if component_id not in trait_sources[trait_id]:
                trait_sources[trait_id].append(component_id)

    internal_conflicts: list[dict] = []
    if traits_data is not None:
        seen_conflict_pairs: set[frozenset[str]] = set()
        for left in sorted(effective):
            left_def = traits_data.get("traits", {}).get(left) or {}
            for right in left_def.get("separate_from") or []:
                if right not in effective:
                    continue
                pair_key = frozenset([left, right])
                if pair_key in seen_conflict_pairs:
                    continue
                seen_conflict_pairs.add(pair_key)
                conflict = {
                    "type": "intra_product_trait_conflict",
                    "trait": left,
                    "conflicts_with": right,
                    "substances": list(trait_sources.get(left, [])),
                    "conflicting_substances": list(trait_sources.get(right, [])),
                }
                internal_conflicts.append(conflict)

    return effective, trait_sources, internal_conflicts


def load_substance_registry() -> dict[str, dict]:
    substances: dict[str, dict] = {}
    for sf in sorted(SUBSTANCES_DIR.glob("*.yaml")):
        substance, err = load_substance(sf)
        if err:
            print(f"plan: skipping substance card: {err}", file=sys.stderr)
            continue
        sid = substance.get("id")
        if isinstance(sid, str):
            substances[sid] = substance
    return substances


def load_product_registry() -> dict[str, dict]:
    products: dict[str, dict] = {}
    for pf in sorted(PRODUCTS_DIR.glob("*.yaml")):
        product, err = load_product(pf)
        if err:
            print(f"plan: skipping product card: {err}", file=sys.stderr)
            continue
        pid = product.get("id")
        if isinstance(pid, str):
            products[pid] = product
    return products


def product_component_substances(product: dict) -> list[str]:
    return [
        component["substance"]
        for component in product.get("components", [])
        if isinstance(component, dict) and isinstance(component.get("substance"), str)
    ]


def format_substance_name(substance: dict) -> str:
    name = str(substance.get("name") or substance.get("id") or "unknown")
    form = substance.get("form")
    if isinstance(form, str) and form:
        return f"{name} ({form})"
    return name


def format_product_name(product: dict) -> str:
    name = str(product.get("name") or product.get("id") or "unknown product")
    brand = product.get("brand")
    if isinstance(brand, str) and brand and brand != "unknown":
        return f"{brand} - {name}"
    return name


def format_item_product_name(
    item_id: str,
    item_products: dict[str, str],
    products: dict[str, dict],
) -> str:
    product_id = item_products[item_id]
    return format_product_name(products.get(product_id) or {"id": product_id})


def readable_traits(trait_ids: set[str], traits_data: dict) -> list[str]:
    labels: list[str] = []
    trait_defs = traits_data.get("traits", {}) if isinstance(traits_data, dict) else {}
    for trait_id in sorted(trait_ids):
        if trait_id == "risk:manual_review":
            continue
        trait = trait_defs.get(trait_id) or {}
        label = trait.get("label") if isinstance(trait, dict) else None
        labels.append(str(label or trait_id))
    return sorted(labels, key=str.casefold)


def explain_slot_choice(
    trait_ids: set[str],
    slot: dict,
    traits_data: dict,
) -> list[str]:
    notes: list[str] = []
    trait_defs = traits_data.get("traits", {}) if isinstance(traits_data, dict) else {}
    for trait_id in sorted(trait_ids):
        trait = trait_defs.get(trait_id)
        if not isinstance(trait, dict):
            continue
        label = str(trait.get("label") or trait_id)
        has_positive_preference = False
        positive_preference_matched = False
        tradeoff_matched = False
        for effect in trait.get("effects") or []:
            if not isinstance(effect, dict):
                continue
            level = effect.get("level")
            if level in {"prefer", "prefer_strong"}:
                has_positive_preference = True
            match = effect.get("match") or {}
            if not isinstance(match, dict) or not slot_matches(slot, match):
                continue
            if effect.get("block") is True:
                notes.append(f"{label}: blocked incompatible slots.")
            elif level in {"avoid", "avoid_strong"}:
                tradeoff_matched = True
                notes.append(f"{label}: tradeoff; this slot is not ideal for that preference.")
            elif level in {"prefer", "prefer_strong"}:
                positive_preference_matched = True
                notes.append(f"{label}: fits this slot.")
        if has_positive_preference and not positive_preference_matched and not tradeoff_matched:
            notes.append(f"{label}: tradeoff; preferred slot condition was not available here.")
    return sorted(set(notes), key=str.casefold) or [
        "No strict timing driver; placed in an available compatible slot."
    ]


def build_substance_slot_names(
    *,
    slot_items: list[str],
    item_products: dict[str, str],
    products: dict[str, dict],
    substances: dict[str, dict],
) -> list[str]:
    names: set[str] = set()
    for item_id in slot_items:
        product_id = item_products[item_id]
        product = products[product_id]
        for component in product.get("components") or []:
            if not isinstance(component, dict):
                continue
            substance_id = component.get("substance")
            if not isinstance(substance_id, str):
                continue
            substance = substances.get(substance_id) or {}
            names.add(format_substance_name(substance))
    return sorted(names, key=str.casefold)


def slot_matches(slot: dict, match_pattern: dict) -> bool:
    """AND-only: slot satisfies match if all listed fields equal."""
    for key, value in match_pattern.items():
        if slot.get(key) != value:
            return False
    return True


def compute_slot_score(
    trait_ids: set[str],
    slot: dict,
    traits_data: dict,
    trait_sources: dict[str, list[str]] | None = None,
) -> tuple[int, bool, list[str]]:
    """Returns (score, blocked, reasons)."""
    score = 0
    blocked = False
    reasons: list[str] = []
    for trait_id in sorted(trait_ids):
        trait = traits_data.get("traits", {}).get(trait_id)
        if not trait:
            continue
        for eff in trait.get("effects") or []:
            match_pattern = eff.get("match", {})
            if not slot_matches(slot, match_pattern):
                continue
            source_text = ""
            if trait_sources is not None:
                sources = trait_sources.get(trait_id) or ["unknown"]
                source_text = f" from {', '.join(sources)}"
            if eff.get("block") is True:
                blocked = True
                reasons.append(f"{trait_id}{source_text} BLOCK on match {match_pattern}")
            elif "level" in eff:
                level = eff["level"]
                delta = LEVEL_SCORES.get(level, 0)
                score += delta
                reasons.append(
                    f"{trait_id}{source_text} match {match_pattern} -> "
                    f"{level} ({delta:+d})"
                )
    return score, blocked, reasons


def must_separate(t1: set[str], t2: set[str], traits_data: dict) -> bool:
    """Symmetric: t1 and t2 share a slot conflict if either declares separate_from
    referencing a trait in the other."""
    def declares_against(traits_a: set[str], traits_b: set[str]) -> bool:
        for trait_id in traits_a:
            trait = traits_data.get("traits", {}).get(trait_id)
            if not trait:
                continue
            for sep in trait.get("separate_from") or []:
                if sep in traits_b:
                    return True
        return False

    return declares_against(t1, t2) or declares_against(t2, t1)


def cmd_plan() -> int:
    # Implicit check first
    print("=== running check ===", file=sys.stderr)
    check_result = cmd_check()
    if check_result != 0:
        print("plan aborted: check failed; fix errors above and retry.", file=sys.stderr)
        return check_result
    print("=== check passed; building schedule ===", file=sys.stderr)

    slots_data = load_yaml(DATA_DIR / "pillboxes.yaml")
    traits_data = load_yaml(DATA_DIR / "traits.yaml")
    inventory_data = load_yaml(INVENTORY_PATH)

    if not (
        isinstance(slots_data, dict)
        and isinstance(traits_data, dict)
        and isinstance(inventory_data, dict)
    ):
        print("plan: data file not a mapping", file=sys.stderr)
        return 1

    slots: dict[str, dict] = dict(
        sorted(
            flatten_pillbox_slots(slots_data).items(),
            key=lambda kv: (
                kv[1].get("pillbox", ""),
                kv[1].get("order", 0),
            ),
        )
    )

    substances = load_substance_registry()
    products = load_product_registry()
    goal_files = sorted(GOALS_DIR.glob("*.yaml")) if GOALS_DIR.exists() else []
    inventory_entries = normalize_inventory_entries(inventory_data)

    # Non-inactive inventory items + effective traits aggregated from product components
    active: dict[str, set[str]] = {}
    item_products: dict[str, str] = {}
    active_components: dict[str, list[str]] = {}
    trait_sources_by_item: dict[str, dict[str, list[str]]] = {}
    intra_product_conflicts_by_item: dict[str, list[dict]] = {}
    intra_product_relation_conflicts_by_item: dict[str, list[dict]] = {}
    item_stacks: dict[str, str] = {}
    for item_id, entry in inventory_entries.items():
        stack = entry.get("stack")
        if stack == "inactive":
            continue
        product_id = entry.get("product")
        product = products.get(product_id)
        if not product:
            print(
                f"plan: skipping '{item_id}' — product '{product_id}' missing or invalid",
                file=sys.stderr,
            )
            continue
        effective, trait_sources, internal_conflicts = effective_inventory_traits(
            product, substances, traits_data
        )
        active[item_id] = effective
        item_products[item_id] = product_id
        active_components[item_id] = product_component_substances(product)
        trait_sources_by_item[item_id] = trait_sources
        intra_product_conflicts_by_item[item_id] = internal_conflicts
        intra_product_relation_conflicts_by_item[item_id] = (
            collect_intra_product_relation_conflicts(
                item_id=item_id,
                product_id=product_id,
                component_ids=active_components[item_id],
                substances=substances,
                relation_type="competes",
            )
        )
        item_stacks[item_id] = stack

    if not active:
        print("plan: no non-inactive inventory items.", file=sys.stderr)
        return 1

    workout_stacks = {
        slot.get("inventory_stack")
        for slot in slots.values()
        if str(slot.get("near", "")).startswith("workout_")
        and isinstance(slot.get("inventory_stack"), str)
    }
    for item_id, traits in active.items():
        activity_traits = sorted(trait for trait in traits if trait.startswith("activity:"))
        if activity_traits and item_stacks[item_id] not in workout_stacks:
            print(
                f"plan: inventory item '{item_id}' has {', '.join(activity_traits)} "
                f"but stack '{item_stacks[item_id]}' has no workout pillbox slots.",
                file=sys.stderr,
            )
            return 1

    # Symmetric prefer_with pairs between schedulable product-backed inventory items.
    prefer_pairs: set[frozenset[str]] = set()
    ambiguous_prefer_with_warnings: list[dict] = []
    substance_to_active_items: dict[str, list[str]] = {}
    for item_id, component_ids in active_components.items():
        for component_id in component_ids:
            substance_to_active_items.setdefault(component_id, []).append(item_id)
    for component_id in substance_to_active_items:
        substance_to_active_items[component_id].sort()

    for item_id, component_ids in active_components.items():
        for component_id in component_ids:
            substance = substances.get(component_id) or {}
            for target_substance in substance.get("prefer_with") or []:
                target_items = substance_to_active_items.get(target_substance, [])
                if len(target_items) == 1:
                    other_item = target_items[0]
                    if other_item != item_id:
                        prefer_pairs.add(frozenset([item_id, other_item]))
                elif len(target_items) > 1:
                    ambiguous_prefer_with_warnings.append(
                        {
                            "type": "ambiguous_prefer_with",
                            "item": item_id,
                            "product": item_products[item_id],
                            "source_substance": component_id,
                            "target_substance": target_substance,
                            "candidate_items": target_items,
                            "message": (
                                "prefer_with target maps to multiple active "
                                "inventory items; no bonus awarded"
                            ),
                        }
                    )

    # Candidate slots per inventory item: list of (slot_name, score, reasons)
    candidates: dict[str, list[tuple[str, int, list[str]]]] = {}
    for sid, traits in active.items():
        valid: list[tuple[str, int, list[str]]] = []
        for slot_name, slot in slots.items():
            if slot.get("inventory_stack") != item_stacks[sid]:
                continue
            score, blocked, reasons = compute_slot_score(
                traits, slot, traits_data, trait_sources_by_item[sid]
            )
            if blocked:
                continue
            valid.append((slot_name, score, reasons))
        if not valid:
            print(
                f"plan: inventory item '{sid}' is blocked from every slot.",
                file=sys.stderr,
            )
            return 1
        valid.sort(key=lambda c: -c[1])  # best score first
        candidates[sid] = valid

    # === Exhaustive global search over the small candidate space ===
    slot_names = list(slots)
    slot_order = {slot_name: index for index, slot_name in enumerate(slot_names)}
    active_order = list(active)
    sorted_items = sorted(
        active,
        key=lambda item: (
            len(candidates[item]),
            -max(score for _slot_name, score, _reasons in candidates[item]),
            active_order.index(item),
        ),
    )
    candidate_scores = {
        item: {slot_name: score for slot_name, score, _reasons in item_candidates}
        for item, item_candidates in candidates.items()
    }
    remaining_max_scores: list[int] = [0] * (len(sorted_items) + 1)
    for index in range(len(sorted_items) - 1, -1, -1):
        item = sorted_items[index]
        remaining_max_scores[index] = remaining_max_scores[index + 1] + max(
            candidate_scores[item].values()
        )

    assignment: dict[str, str] = {}
    slot_traits: dict[str, list[set[str]]] = {slot_name: [] for slot_name in slots}
    slot_items: dict[str, list[str]] = {slot_name: [] for slot_name in slots}
    slot_counts: dict[str, int] = {slot_name: 0 for slot_name in slots}
    best_assignment: dict[str, str] | None = None
    best_key: tuple[int, ...] | None = None
    best_metrics: tuple[float, int, int, float] | None = None

    def assignment_tie_key(candidate_assignment: dict[str, str]) -> tuple[int, ...]:
        return tuple(slot_order[candidate_assignment[item]] for item in active_order)

    def balance_lower_bound(search_index: int) -> float:
        relaxed_counts = dict(slot_counts)
        remaining_by_stack: dict[str, int] = {}
        for item in sorted_items[search_index:]:
            remaining_by_stack[item_stacks[item]] = remaining_by_stack.get(
                item_stacks[item], 0
            ) + 1
        for stack, remaining_count in remaining_by_stack.items():
            stack_slots = [
                slot_name
                for slot_name, slot in slots.items()
                if slot.get("inventory_stack") == stack
            ]
            for _ in range(remaining_count):
                target = min(stack_slots, key=lambda slot_name: relaxed_counts[slot_name])
                relaxed_counts[target] += 1
        return BALANCE_WEIGHT * sum(count * count for count in relaxed_counts.values())

    def evaluate_complete(slot_score_total: int) -> tuple[float, int, int, float]:
        prefer_with_bonus = 0
        for pair in prefer_pairs:
            a, b = tuple(pair)
            if assignment.get(a) == assignment.get(b):
                prefer_with_bonus += PREFER_WITH_BONUS
        balance_penalty = BALANCE_WEIGHT * sum(
            count * count for count in slot_counts.values()
        )
        total = slot_score_total + prefer_with_bonus - balance_penalty
        return total, slot_score_total, prefer_with_bonus, balance_penalty

    def seed_with_greedy_assignment() -> None:
        nonlocal best_assignment, best_key, best_metrics

        greedy_assignment: dict[str, str] = {}
        greedy_slot_traits: dict[str, list[set[str]]] = {
            slot_name: [] for slot_name in slots
        }
        greedy_slot_items: dict[str, list[str]] = {slot_name: [] for slot_name in slots}
        greedy_slot_counts: dict[str, int] = {slot_name: 0 for slot_name in slots}
        greedy_slot_score = 0
        for item in sorted_items:
            traits = active[item]
            chosen: tuple[str, int] | None = None
            for slot_name, score, _reasons in sorted(
                candidates[item],
                key=lambda candidate: (-candidate[1], slot_order[candidate[0]]),
            ):
                if any(
                    must_separate(traits, existing_traits, traits_data)
                    for existing_traits in greedy_slot_traits[slot_name]
                ):
                    continue
                if any(
                    component_sets_have_relation(
                        active_components[item],
                        active_components[existing_item],
                        substances,
                        "competes",
                    )
                    for existing_item in greedy_slot_items[slot_name]
                ):
                    continue
                chosen = slot_name, score
                break
            if chosen is None:
                return
            slot_name, score = chosen
            greedy_assignment[item] = slot_name
            greedy_slot_traits[slot_name].append(traits)
            greedy_slot_items[slot_name].append(item)
            greedy_slot_counts[slot_name] += 1
            greedy_slot_score += score

        prefer_with_bonus = 0
        for pair in prefer_pairs:
            a, b = tuple(pair)
            if greedy_assignment.get(a) == greedy_assignment.get(b):
                prefer_with_bonus += PREFER_WITH_BONUS
        balance_penalty = BALANCE_WEIGHT * sum(
            count * count for count in greedy_slot_counts.values()
        )
        total = greedy_slot_score + prefer_with_bonus - balance_penalty
        best_assignment = greedy_assignment
        best_metrics = (
            total,
            greedy_slot_score,
            prefer_with_bonus,
            balance_penalty,
        )
        best_key = assignment_tie_key(greedy_assignment)

    def search(index: int, slot_score_total: int) -> None:
        nonlocal best_assignment, best_key, best_metrics

        if best_metrics is not None:
            optimistic_total = (
                slot_score_total
                + remaining_max_scores[index]
                + len(prefer_pairs) * PREFER_WITH_BONUS
                - balance_lower_bound(index)
            )
            if optimistic_total < best_metrics[0] - 1e-9:
                return

        if index == len(sorted_items):
            metrics = evaluate_complete(slot_score_total)
            candidate_key = assignment_tie_key(assignment)
            if (
                best_metrics is None
                or metrics[0] > best_metrics[0] + 1e-9
                or (
                    abs(metrics[0] - best_metrics[0]) <= 1e-9
                    and (best_key is None or candidate_key < best_key)
                )
            ):
                best_metrics = metrics
                best_assignment = dict(assignment)
                best_key = candidate_key
            return

        item = sorted_items[index]
        traits = active[item]
        ordered_candidates = sorted(
            candidates[item],
            key=lambda candidate: (-candidate[1], slot_order[candidate[0]]),
        )
        for slot_name, score, _reasons in ordered_candidates:
            if any(
                must_separate(traits, existing_traits, traits_data)
                for existing_traits in slot_traits[slot_name]
            ):
                continue
            if any(
                component_sets_have_relation(
                    active_components[item],
                    active_components[existing_item],
                    substances,
                    "competes",
                )
                for existing_item in slot_items[slot_name]
            ):
                continue
            assignment[item] = slot_name
            slot_traits[slot_name].append(traits)
            slot_items[slot_name].append(item)
            slot_counts[slot_name] += 1
            search(index + 1, slot_score_total + score)
            slot_counts[slot_name] -= 1
            slot_items[slot_name].pop()
            slot_traits[slot_name].pop()
            del assignment[item]

    seed_with_greedy_assignment()
    search(0, 0)

    if best_assignment is None or best_metrics is None:
        print(
            "plan: no valid global assignment under slot conflict constraints.",
            file=sys.stderr,
        )
        return 1

    assignment = best_assignment
    _final_total, _slot_score_sum, prefer_bonus, _balance_pen = best_metrics

    # Build schedule.yaml
    schedule: dict = {
        "version": 1,
        "summary": {},
        "action_points": [],
        "review_contexts": [],
        "placement_notes": [],
        "pillboxes": build_empty_schedule_pillboxes(slots_data),
        "goals": [],
        "warnings": [],
        "kept_together": [
            {
                "pair": sorted([
                    format_item_product_name(item_id, item_products, products)
                    for item_id in sorted(p)
                ], key=str.casefold),
                "together": (
                    assignment[sorted(p)[0]] == assignment[sorted(p)[1]]
                ),
                "slot": assignment[sorted(p)[0]]
                if assignment[sorted(p)[0]] == assignment[sorted(p)[1]]
                else None,
            }
            for p in (sorted(prefer_pairs, key=lambda x: sorted(x)))
        ],
        "explanations": {},
    }

    for sid in active_order:
        slot_name = assignment[sid]
        pillbox_name = str(slots[slot_name].get("pillbox"))
        schedule["pillboxes"][pillbox_name]["slots"][slot_name]["products"].append(
            format_item_product_name(sid, item_products, products)
        )
    for pillbox in schedule["pillboxes"].values():
        for slot_entry in pillbox["slots"].values():
            slot_entry["products"] = sorted(slot_entry["products"], key=str.casefold)

    for slot_name, slot in slots.items():
        pillbox_name = str(slot.get("pillbox"))
        slot_entry = schedule["pillboxes"][pillbox_name]["slots"][slot_name]
        slot_item_ids = [
            item_id for item_id in active_order if assignment[item_id] == slot_name
        ]
        slot_entry["substances"] = build_substance_slot_names(
            slot_items=slot_item_ids,
            item_products=item_products,
            products=products,
            substances=substances,
        )

    active_substance_ids = set(substance_to_active_items)
    inactive_product_ids = {
        entry["product"]
        for entry in inventory_entries.values()
        if (
            isinstance(entry, dict)
            and entry.get("stack") == "inactive"
            and isinstance(entry.get("product"), str)
        )
    }
    inactive_substance_ids = collect_product_substance_refs(products, inactive_product_ids)
    schedule["goals"] = build_goal_review(
        goal_files=goal_files,
        active_substances=active_substance_ids,
        inactive_substances=inactive_substance_ids,
        substances=substances,
    )

    for sid in active_order:
        slot_name = assignment[sid]
        slot = slots[slot_name]
        product_name = format_item_product_name(sid, item_products, products)
        schedule["explanations"][product_name] = {
            "components": [
                format_substance_name(substances.get(substance_id) or {"id": substance_id})
                for substance_id in active_components[sid]
            ],
            "pillbox": slot.get("pillbox"),
            "slot": slot_name,
            "why_here": explain_slot_choice(active[sid], slot, traits_data),
            "review_tags": readable_traits(active[sid], traits_data),
        }

    for sid, internal_conflicts in intra_product_conflicts_by_item.items():
        for conflict in internal_conflicts:
            schedule["warnings"].append(
                {
                    "type": "intra_product_trait_conflict",
                    "item": sid,
                    "product": item_products[sid],
                    "trait": conflict["trait"],
                    "conflicts_with": conflict["conflicts_with"],
                    "substances": conflict["substances"],
                    "conflicting_substances": conflict["conflicting_substances"],
                    "message": (
                        "Component traits conflict inside one physical product; "
                        "scheduling keeps the product together and emits this warning"
                    ),
                }
            )
    for sid, internal_conflicts in intra_product_relation_conflicts_by_item.items():
        for conflict in internal_conflicts:
            schedule["warnings"].append(conflict)

    schedule["warnings"].extend(
        collect_active_unmatched_concerns(
            active_order=active_order,
            active_components=active_components,
            item_products=item_products,
            products=products,
            substances=substances,
        )
    )
    schedule["warnings"].extend(ambiguous_prefer_with_warnings)

    for sid, traits in active.items():
        for trait_id in sorted(traits):
            trait_def = traits_data.get("traits", {}).get(trait_id)
            if trait_def and trait_def.get("warning"):
                for source in trait_sources_by_item[sid].get(trait_id) or ["unknown"]:
                    schedule["warnings"].append(
                        {
                            "item": sid,
                            "product": item_products[sid],
                            "substance": source,
                            "trait": trait_id,
                            "message": trait_def.get(
                                "description", "Manual review required."
                            ),
                            "action": trait_def.get("action", ""),
                        }
                    )

    for warning in collect_missing_balance_relations(
        substances, active_substance_ids
    ):
        schedule["warnings"].append(warning)
    for warning in collect_missing_support_relations(
        substances, active_substance_ids
    ):
        schedule["warnings"].append(warning)

    schedule["warnings"] = [
        humanize_warning(warning, products=products, substances=substances)
        for warning in schedule["warnings"]
        if not is_generic_manual_review_warning(warning)
    ]
    schedule["action_points"] = build_action_points(schedule["warnings"])
    schedule["review_contexts"] = build_review_contexts(schedule["warnings"])
    schedule["placement_notes"] = build_placement_notes(schedule)
    schedule["summary"] = build_schedule_summary(schedule)

    SCHEDULE_PATH.write_text(dump_schedule_yaml(schedule))

    slot_loads = {
        f"{pillbox_name}.{slot_name}": len(slot_entry["products"])
        for pillbox_name, pillbox in schedule["pillboxes"].items()
        for slot_name, slot_entry in pillbox["slots"].items()
    }
    print(f"\nschedule written to {SCHEDULE_PATH}")
    print(f"slot loads: {slot_loads}")
    print(
        f"kept_together pairs: {len(prefer_pairs)} declared, "
        f"{prefer_bonus // PREFER_WITH_BONUS} together"
    )
    print(f"warnings: {len(schedule['warnings'])}")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Supplement Slot Planner",
        epilog=(
            "Agent workflows:\n"
            "  Data-only YAML edits:\n"
            "    uv run planner.py check\n"
            "    uv run planner.py doctor\n\n"
            "  Schedule-affecting edits:\n"
            "    uv run planner.py plan\n"
            "    uv run planner.py doctor\n\n"
            "  Planner, schema, or test changes:\n"
            "    uv run planner.py plan\n"
            "    uv run planner.py doctor\n"
            "    uv run pytest\n"
            "    uv run planner.py plan\n\n"
            "Notes:\n"
            "  check, plan, and doctor automatically generate missing product/substance\n"
            "  ids and rename product/substance files when that fix is deterministic.\n"
            "  plan runs check first and rewrites schedule.yaml."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="cmd", required=False)

    sub.add_parser("check", help="validate all YAML data files")

    sub.add_parser("plan", help="generate schedule.yaml from non-inactive inventory")
    sub.add_parser("doctor", help="list cleanup and refactor candidates")

    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(0)

    args = parser.parse_args()

    if args.cmd == "check":
        sys.exit(cmd_check())
    elif args.cmd == "plan":
        sys.exit(cmd_plan())
    elif args.cmd == "doctor":
        sys.exit(cmd_doctor())


if __name__ == "__main__":
    main()
