"""Solver-owned schedule serialization and atomic publication."""

from __future__ import annotations

import contextlib
import os
import tempfile
import uuid
from pathlib import Path

import yaml

from planner.canonical_optimizer_result import Diagnostic, Indeterminate
from planner.schedule_types import CanonicalPublicationSource, CanonicalScheduleData, PublishedSchedule

SCHEDULE_COMMENTS = {
    "summary": ["Generated by `uv run python -m planner`; edit source cards under data/, not this file."],
    "status": ["Only an exact globally optimal layout is publishable."],
    "objective": ["Exact objective: pressure satisfaction, squared load, stable assignment key."],
    "assignments": ["Stable canonical item-to-logical-slot assignment proved by the exact optimizer."],
    "pressure_matches": ["Typed normalized pressure matches and their proof records."],
    "domain_loads": ["Exact per-domain integer loads and optimizer proof records."],
    "optimizer_proof": ["Proof records emitted by the exact canonical optimizer."],
    "canonical_explanations": ["Typed facts, anchors, and optimizer proof without authored placement prose."],
}


class NoAliasSafeDumper(yaml.SafeDumper):
    def ignore_aliases(self, data: object) -> bool:
        return True


def dump_schedule_yaml(schedule: CanonicalScheduleData) -> str:
    """Serialize the sole writer-derived schedule document."""
    rendered = yaml.dump(
        schedule, Dumper=NoAliasSafeDumper, sort_keys=False, default_flow_style=False, allow_unicode=True
    )
    lines: list[str] = []
    for line in rendered.splitlines():
        key = line.split(":", 1)[0] if line and not line.startswith(" ") else ""
        if key in SCHEDULE_COMMENTS:
            lines.extend(f"# {comment}" for comment in SCHEDULE_COMMENTS[key])
        lines.append(line)
    return "\n".join(lines) + "\n"


def invalidate_schedule_file(schedule_file: Path) -> None:
    """Remove the volatile current-layout lease, if one exists."""
    schedule_file.unlink(missing_ok=True)


def write_schedule_file(schedule_file: Path, source: CanonicalPublicationSource) -> PublishedSchedule | Indeterminate:
    """Optimize exactly once, derive, fsync, and atomically install a schedule.

    No precomputed answer can cross this boundary: the only input is the frozen
    world-fact source. Any malformed source or publication failure leaves no
    current layout lease behind.
    """
    tmp_schedule_file: Path | None = None
    fd: int | None = None
    published = False
    try:
        invalidate_schedule_file(schedule_file)
        if not isinstance(source, CanonicalPublicationSource):
            raise TypeError("write_schedule_file requires a CanonicalPublicationSource")
        # Import lazily: this module is also needed by the command package
        # while it initializes its public plan entrypoint.
        from planner.canonical_optimizer import CanonicalOptimizerInput, optimize_canonical_layout
        from planner.canonical_output import build_canonical_schedule_document

        result = optimize_canonical_layout(
            CanonicalOptimizerInput(
                item_domains=source.item_domains,
                slots=source.slots,
                pressures=source.inference.pressures,
                pressure_values_by_dimension=source.pressure_values_by_dimension,
            )
        )
        if isinstance(result, Indeterminate):
            return result
        document = build_canonical_schedule_document(source, result)
        rendered = dump_schedule_yaml(document)
        fd, tmp_name = tempfile.mkstemp(
            prefix=f"{schedule_file.name}.tmp.{os.getpid():x}.{uuid.uuid4().hex}.", dir=schedule_file.parent, text=True
        )
        tmp_schedule_file = Path(tmp_name)
        stream = os.fdopen(fd, "w", encoding="utf-8")
        fd = None
        with stream:
            stream.write(rendered)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(tmp_schedule_file, schedule_file)  # noqa: PTH105
        published = True
        return PublishedSchedule(document, result)
    except KeyboardInterrupt, MemoryError:
        raise
    except Exception as error:  # noqa: BLE001
        return Indeterminate(Diagnostic("publication_failed", f"canonical publication failed closed: {error}"))
    finally:
        if fd is not None:
            with contextlib.suppress(OSError):
                os.close(fd)
        if tmp_schedule_file is not None:
            with contextlib.suppress(OSError):
                tmp_schedule_file.unlink(missing_ok=True)
        # Every non-published result invalidates any old lease, including a
        # partial temporary/write failure.  A successful replace is preserved.
        # `result` is not visible here on every exception, so inspect ownership.
        if not published:
            with contextlib.suppress(OSError):
                invalidate_schedule_file(schedule_file)


def schedule_slot_loads(schedule: CanonicalScheduleData) -> dict[str, int]:
    return {
        f"{pillbox_name}.{slot_name}": len(slot_entry["products"])
        for pillbox_name, pillbox in schedule["pillboxes"].items()
        for slot_name, slot_entry in pillbox["slots"].items()
    }
