"""schedule.yaml serialization."""

from __future__ import annotations

import contextlib
import os
import tempfile
import uuid
from pathlib import Path

import yaml

from planner.schedule_types import CanonicalScheduleData, OptimalPublication

SCHEDULE_COMMENTS = {
    "summary": [
        "Generated by `uv run python -m planner`; edit source cards under data/, not this file.",
        "Short human-facing summary.",
        "`take` is grouped by pillbox so daily and training products do not read as one regimen.",
        "`usage_groups` separates daily-base and not-every-day presentation without changing `take`.",
    ],
    "placement_notes": [
        "Non-warning placement compromises.",
        "These explain acceptable but imperfect slot choices; they are not safety warnings.",
    ],
    "pillboxes": [
        "Planned pillboxes and their intake slots.",
        "`products` lists scheduled product names; `substances` expands those products for human review.",
    ],
    "benefits": [
        "Benefit goal membership overview.",
        "`members` separates relevance, product tracking, and usage state; expert gaps are not inferred here.",
    ],
    "risks": [
        "Risk load membership overview.",
        "`members` separates relevance, product tracking, and usage state; expert severity is not inferred here.",
    ],
    "active_fact_index": [
        "Fact-first active-stack index for agents.",
        "Each entry is an existing substance knowledge fact projected to active products.",
        "This section is evidence only: no roles, rankings, recommendations, or generated questions.",
    ],
    "warnings": [
        "Detailed review warnings.",
        "Warnings are prompts for human review; they are not medical advice.",
    ],
    "status": [
        "Closed canonical publication status; only `Optimal` documents are publishable.",
    ],
    "objective": [
        "Exact canonical objective: unique pressure satisfaction, integer squared load, stable assignment key.",
    ],
    "assignments": [
        "Stable canonical item-to-logical-slot assignment proved by the exact optimizer.",
    ],
    "pressure_matches": [
        "Typed normalized pressure matches and their fact, law, applicability, and provenance records.",
    ],
    "domain_loads": [
        "Exact per-domain integer slot loads and optimizer proof records.",
    ],
    "optimizer_proof": [
        "Proof records emitted by the exact canonical optimizer.",
    ],
    "canonical_explanations": [
        "Structured canonical placement explanations from typed facts, laws, anchors, and optimizer proofs.",
    ],
}


class NoAliasSafeDumper(yaml.SafeDumper):
    """Safe YAML dumper for human-facing generated output."""

    def ignore_aliases(self, data: object) -> bool:
        return True


def dump_schedule_yaml(schedule: CanonicalScheduleData) -> str:
    """Serialise schedule and inject comment blocks above top-level keys."""
    rendered = yaml.dump(
        schedule,
        Dumper=NoAliasSafeDumper,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
    )
    lines: list[str] = []
    for line in rendered.splitlines():
        key = line.split(":", 1)[0] if line and not line.startswith(" ") else ""
        if key in SCHEDULE_COMMENTS:
            lines.extend(f"# {comment}" for comment in SCHEDULE_COMMENTS[key])
        lines.append(line)
    return "\n".join(lines) + "\n"


def write_schedule_file(schedule_file: Path, publication: OptimalPublication) -> None:
    """Atomically publish one proved canonical schedule document.

    Rendering occurs before creating the temporary file.  The temporary file
    is unique per invocation and is removed for every failure path, leaving an
    existing schedule byte-for-byte untouched unless the final replace works.
    """
    if not isinstance(publication, OptimalPublication):
        raise TypeError("write_schedule_file requires an OptimalPublication")
    publication.validate()
    rendered = dump_schedule_yaml(publication.document)
    fd, tmp_name = tempfile.mkstemp(
        prefix=f"{schedule_file.name}.tmp.{os.getpid():x}.{uuid.uuid4().hex}.",
        dir=schedule_file.parent,
        text=True,
    )
    tmp_schedule_file = Path(tmp_name)
    fd_open = True
    try:
        stream = os.fdopen(fd, "w", encoding="utf-8")
        fd_open = False
        with stream:
            stream.write(rendered)
            stream.flush()
            os.fsync(stream.fileno())
        tmp_schedule_file.replace(schedule_file)
    except BaseException:
        if fd_open:
            with contextlib.suppress(OSError):
                os.close(fd)
        with contextlib.suppress(OSError):
            tmp_schedule_file.unlink(missing_ok=True)
        raise


def schedule_slot_loads(schedule: CanonicalScheduleData) -> dict[str, int]:
    """Return product counts per pillbox slot."""
    return {
        f"{pillbox_name}.{slot_name}": len(slot_entry["products"])
        for pillbox_name, pillbox in schedule["pillboxes"].items()
        for slot_name, slot_entry in pillbox["slots"].items()
    }
